# 支持项目

这个项目的维护完全靠志愿者。如果你认为这个项目对你有帮助，请考虑支持：

github: [liny]
# patreon: # 替换为你的 Patreon 用户名
# open_collective: # 替换为你的 Open Collective 用户名
# ko_fi: # 替换为你的 Ko-fi 用户名
# tidelift: # 替换为你的 Tidelift 包管理器/包名
# community_bridge: # 替换为你的 Community Bridge 项目名称
# liberapay: # 替换为你的 Liberapay 用户名
# issuehunt: # 替换为你的 IssueHunt 用户名
# otechie: # 替换为你的 Otechie 用户名
# custom: # 自定义 URL
